### PR TITLE
fix when json not content is not ready

### PR DESCRIPTION
**Pull request by sguiheux**

### CODE REVIEW

**Review by matiboy — CHANGES_REQUESTED** [review]
Hi @sguiheux Thanks for this. However !json would also catch empty strings, 0 and false. Could you please change to make it match only undefined?
And maybe we should return a span with a "undefined" class, more like the rest of the highlighter, what do you think?
Thanks!

**Comment by sguiheux** [comment]
Ok i Will do that :-)

**Comment by sguiheux** [comment]
done

**Review by matiboy — APPROVED** [review]

**Comment by matiboy** [comment]
Thanks @sguiheux

**Pull request merged**
